pipeline {
    agent any

    stages {
        stage('Launch application') {
            agent {
                docker {
                    image 'docker:28.3.3'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u root --privileged'
                }
            }
            steps {
                sh '''
                    chmod 666 /var/run/docker.sock || true
                    docker compose up --build -d
                '''
            }
        }

        stage('E2E tests') {
            agent {
                docker {
                    image 'docker:28.3.3'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u root --privileged'
                }
            }
            steps {
                dir('tests-e2e') {
                    sh '''
                        npm install
                        npx playwright test
                    '''
                }
            }
            post {
                always {
                    junit 'tests-e2e/test-results/results.xml'
                    publishHTML target:([
                        reportDir: 'tests-e2e/playwright-report',
                        reportNames: 'index.html',
                        reportName: 'Playwright E2E tests',
                    ])
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}