pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'golang:1.21-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage('Unit tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test    
                    '''
                }
            }
        }
    }
}
