pipeline {
    agent any

    stages {
        stage('Unit tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE = '/tmp/go-cache'
                GOPATH = '/tmp/go'
                CGO_ENABLED = '0'
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p /tmp/go-cache /tmp/go
                        go test -v ./...
                    '''
                }
            }
        }

        stage('Unit tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test    
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
