name: CI

on:
  push:
    branches:
      - main

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.test-backend.outputs.report }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: bugtracker-backend/go.sum
      
      - name: Install go junit report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Execute Backend Unit Tests
        id: test-backend  
        working-directory: ./bugtracker-backend
        run: |
          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt

          echo '```' >> $GITHUB_STEP_SUMMURY
          cat coverage.txt >> $GITHUB_STEP_SUMMURY
          echo '```' >> $GITHUB_STEP_SUMMURY

          echo 'report<<EOF' >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

          go test ./... -v 2>&1 | go-junit-report > test-results.xml

      - name: Publish Backend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Tests Report  
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit
            
  unit-tests-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: bugtracker-frontend/package-lock.json
    
      - name: Execute Frontend Unit Tests
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full_output.txt

          echo '```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
       
      - name: Publish Frontend Tests Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests Report  
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit
          
  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [unit-tests-backend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Create Backend Coverage Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Backend Test Coverage Report
            ```
            ${{ needs.unit-tests-backend.outputs.coverage }}
            ```
