name: CI

on:
  push:
    branches:
      - main

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache-dependency-path: bugtracker-backend/go.sum

      - name: Execute Backend Unit Tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./...
  unit-tests-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: bugtracker-frontend/package-lock.json
    
      - name: Execute Frontend Unit Tests
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test
       
      - name: Publish Frontend Tests Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Frontend Unit Tests Report  
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit
